version: "3.8"
services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MYSQL_DATABASE=Robinhood
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=S3cret
    depends_on:
      - db
  db:
    build:
      context: db
      dockerfile: Dockerfile_SQL
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: S3cret
      MYSQL_DATABASE: Robinhood
    ports:
      - "3306:3306"